name: Daily Status Report
on:
  schedule:
    - cron: '0 21 * * *'  # 21:00 UTC (23:00 hora España en verano)
  workflow_dispatch:  # Permite ejecución manual
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Generar reporte
        run: |
          echo "Fecha: $(date +'%d/%m/%Y %H:%M')" >> report.txt
          echo "Progreso del día:" >> report.txt
          echo "- Detección de flexiones: 75% completado" >> report.txt
          echo "- Integración Google Drive: Pendiente" >> report.txt
          echo "Próximo hito: Diseño de UI para menú de comidas." >> report.txt
      - name: Enviar correo
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          curl --ssl-reqd \
            --url "smtp://smtp.gmail.com:587" \
            --user "$EMAIL_USER:$EMAIL_PASSWORD" \
            --mail-from "$EMAIL_USER" \
            --mail-rcpt "iamoctimusengo@gmail.com" \
            --upload-file report.txt
