name: Daily Status Report
on:
  schedule:
    - cron: '0 21 * * *'  # 21:00 UTC (23:00 hora España en verano)
  workflow_dispatch:  # Permite ejecución manual
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Generar reporte
        run: | 
              echo "Fecha: $(date +'%d/%m/%Y %H:%M')" >> report.txt
              echo "Progreso del día:" >> report.txt
              echo "- Detección de flexiones: 75% completado" >> report.txt
            
      - name: Enviar el correo
        env:
            EMAIL_USER: ${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
              # Crear archivo con encabezados y cuerpo
              echo "Subject: [Daily Report] Estado del Proyecto $(date +'%d/%m/%Y')" > message.txt
              echo "From: $EMAIL_USER" >> message.txt
              echo "To: iamoctimusengo@gmail.com" >> message.txt
              echo "Content-Type: text/plain; charset=UTF-8" >> message.txt
              echo "" >> message.txt  # Línea vacía para separar encabezados y cuerpo
              cat report.txt >> message.txt
          
              # Enviar el correo
              curl --ssl-reqd \
                --url "smtps://smtp.gmail.com:465" \
                --user "$EMAIL_USER:$EMAIL_PASSWORD" \
                --mail-from "$EMAIL_USER" \
                --mail-rcpt "iamoctimusengo@gmail.com" \
                --upload-file message.txt
